baseURL = "https://www.posquit0.com"
languageCode = "en-US"
title = "Posquit0"
theme = "awesome-identity"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true


# Add your own params here
[params]
  avatar = "/img/avatar.jpg"
  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = ""
# Google Analytics UA number
  # googleAnalytics = "UA-XXXXX-1"

[params.profile]
  firstname = "Byungjin"
  lastname = "Park"
  title = "Software Architect / Hacker"
  bio = """Current Site Reliability Engineer at start-up company [**Kasa**](http://kasa.network).

  7+ years experience specializing in the backend development, infrastructure automation, and computer hacking/security.

  Super nerd who loves Vim, Linux and OS X and enjoys to customize all of the development environment.

  Interested in devising a better problem-solving method for challenging tasks, and learning new technologies and tools if the need arises."""

[params.contacts]
  email = "posquit0.bj@gmail.com"
  github = "posquit0"
  twitter = "posquit0"
  linkedin = "posquit0"
  keybase = "posquit0"
  # facebook = "posquit0"
  # stackoverflow = "7919458"
  # instagram = "posquit0.bj"
  # medium = "posquit0"
  # quora = "melaozhu"
  # dribbble = "laozhu"
  # behance = "melaozhu"

[params.footer]
  copyright = "© 2019 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true


## Privacy Configurations (GDPR)
[privacy]
  [privacy.googleAnalytics]
    disable = false
    # Make the users’ IP addresses are anonymized within Google Analytics
    anonymizeIP = false
    # Make the GA templates respect the “Do Not Track” HTTP header
    respectDoNotTrack = false
    # Disable the use of Cookies and use Session Storage to Store the GA Client ID
    useSessionStorage = false
