# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Awesome Identity"
license = "MIT"
licenselink = "https://github.com/posquit0/hugo-awesome-identity/blob/master/LICENSE"
description = ""
homepage = "https://github.com/posquit0/hugo-awesome-identity"
tags = ["aboutme", "awesome", "identity"]
features = []
min_version = "0.41"

[author]
  name = "Byungjin Park"
  homepage = "https://www.posquit0.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
